language: php
php:
 - "5.5"
 - "5.6"
 - "hhvm"

before_install:
 - composer self-update
 - composer install --dev --prefer-source

script:
 - ./vendor/bin/php-cs-fixer --version
 - ./vendor/bin/php-cs-fixer fix -v --dry-run
 - phpunit --coverage-clover ./build/coverage/clover.xml

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
