sudo: false
language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
    env:
      - TEST_COVERAGE=true
  - php: 7
    env:
      - CHECK_CS=true
  - php: 7.1
  - php: hhvm
  allow_failures:
  - php: hhvm

cache:
 directories:
 - $HOME/.composer/cache
 - vendor

before_install:
 - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini ; fi
 - travis_retry composer self-update
 - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update scrutinizer/ocular ; fi

install:
 - travis_retry composer install --no-interaction
 - composer show

script:
 - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
 - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi

after_script:
 - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/ocular code-coverage:upload --format=php-clover ./build/coverage/clover.xml ; fi
