<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Thorr\Persistence\Module'                                    => __DIR__ . '/src/Module.php',
  'Thorr\Persistence\Repository\RepositoryEvent'                => __DIR__ . '/src/Repository/RepositoryEvent.php',
  'Thorr\Persistence\Repository\RepositoryInterface'            => __DIR__ . '/src/Repository/RepositoryInterface.php',
  'Thorr\Persistence\Entity\AbstractEntity'                     => __DIR__ . '/src/Entity/AbstractEntity.php',
  'Thorr\Persistence\Entity\IdProviderTrait'                    => __DIR__ . '/src/Entity/IdProviderTrait.php',
  'Thorr\Persistence\Entity\FqcnProviderTrait'                  => __DIR__ . '/src/Entity/FqcnProviderTrait.php',
  'Thorr\Persistence\Doctrine\ObjectManagerAwareTrait'          => __DIR__ . '/src/Doctrine/ObjectManagerAwareTrait.php',
  'Thorr\Persistence\Doctrine\Repository\EntityRepositoryTrait' => __DIR__ . '/src/Doctrine/Repository/EntityRepositoryTrait.php',
  'Thorr\Persistence\Doctrine\Repository\EntityRepository'      => __DIR__ . '/src/Doctrine/Repository/EntityRepository.php',
  'Thorr\Persistence\Doctrine\EntityManagerAwareInterface'      => __DIR__ . '/src/Doctrine/EntityManagerAwareInterface.php',
  'Thorr\Persistence\Doctrine\EntityManagerAwareInitializer'    => __DIR__ . '/src/Doctrine/EntityManagerAwareInitializer.php',
  'Thorr\Persistence\Doctrine\EntityManagerAwareTrait'          => __DIR__ . '/src/Doctrine/EntityManagerAwareTrait.php',
);
